# Generated by Django 2.2.3 on 2019-07-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_auto_20190725_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='key_text',
            new_name='keyword',
        ),
    ]
