# Generated by Django 2.2.3 on 2019-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_auto_20190726_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='uses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
