# Generated by Django 2.2.3 on 2019-08-02 16:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0007_auto_20190802_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='views/media/'), upload_to=''),
        ),
    ]
